# Generated by Django 2.1.3 on 2018-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
