# Generated by Django 2.1.3 on 2018-11-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0004_auto_20181122_0745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
