# Generated by Django 2.1.3 on 2018-11-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0005_auto_20181122_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('content_type', models.CharField(choices=[('A', 'Article'), ('P', 'Page'), ('I', 'Issue')], max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collectable_items',
            },
        ),
        migrations.RemoveField(
            model_name='collection',
            name='content_items',
        ),
        migrations.AddField(
            model_name='collectableitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impresso.Collection'),
        ),
        migrations.AddField(
            model_name='collectableitem',
            name='search_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impresso.SearchQuery', verbose_name='search query'),
        ),
        migrations.AlterUniqueTogether(
            name='collectableitem',
            unique_together={('item_id', 'collection')},
        ),
    ]
