# Generated by Django 2.1.3 on 2018-11-29 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impresso', '0006_auto_20181128_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'creator')},
        ),
    ]
