# Generated by Django 2.1.3 on 2018-11-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0007_auto_20181129_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='count_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='count_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
