# Generated by Django 2.1.3 on 2018-12-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0008_auto_20181130_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectableitem',
            name='search_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impresso.SearchQuery', verbose_name='search query'),
        ),
    ]
