# Generated by Django 2.1.3 on 2018-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0009_auto_20181205_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectableitem',
            name='item_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
