# Generated by Django 2.1.3 on 2019-01-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0011_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REA', 'ready'), ('RUN', 'running'), ('OK', 'Finished, no errors!'), ('ERR', 'Ops, errors!')], default='REA', max_length=3),
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
