# Generated by Django 2.1.5 on 2019-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0012_auto_20190123_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REA', 'ready'), ('RUN', 'running'), ('DON', 'Finished, no errors!'), ('ARC', 'Finished, archived by the user'), ('ERR', 'Ops, errors!')], default='REA', max_length=3),
        ),
    ]
