# Generated by Django 2.1.5 on 2019-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0013_auto_20190123_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
