# Generated by Django 2.1.5 on 2019-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0014_profile_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_corrupted', models.BooleanField(db_column='has_corrupted_json', default=False)),
                ('is_converted', models.BooleanField(db_column='has_converted_coordinates', default=False)),
                ('n_tokens', models.PositiveIntegerField(default=0)),
                ('ocr_quality', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('IDX', 'Index collection in search engine'), ('DCO', 'Delete collection')], max_length=3),
        ),
    ]
