# Generated by Django 2.1.5 on 2019-02-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0015_auto_20190209_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=50)),
                ('content_type', models.CharField(choices=[('A', 'Article'), ('P', 'Page'), ('I', 'Issue')], max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taggable_items',
            },
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_items',
        ),
        migrations.AddField(
            model_name='taggableitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impresso.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='taggableitem',
            unique_together={('item_id', 'tag')},
        ),
    ]
