# Generated by Django 2.1.5 on 2019-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0016_auto_20190219_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectableitem',
            name='item_date',
            field=models.DateField(null=True),
        ),
    ]
