# Generated by Django 2.1.5 on 2019-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0018_auto_20190220_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
