# Generated by Django 2.1.5 on 2019-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0019_profile_email_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('PRI', 'Private'), ('PRI', 'Publicly available - only with a link'), ('PUB', 'Public and indexed'), ('DEL', 'In bin, ready to be deleted. No add items after this change.')], max_length=3),
        ),
    ]
