# Generated by Django 2.1.5 on 2019-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0020_auto_20190228_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_loops_allowed',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_parallel_jobs',
            field=models.IntegerField(default=2),
        ),
    ]
