# Generated by Django 2.1.5 on 2019-03-09 15:52

from django.db import migrations, models
import django.db.models.deletion
import impresso.models.attachment


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0021_auto_20190305_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to=impresso.models.attachment.user_directory_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('DCO', 'Delete collection'), ('IDX', 'Index collection in search engine'), ('EXP', 'Export collection as CSV'), ('EXP', 'Export query as CSV'), ('TES', '10 minutes countdown, 1 percent every 6 seconds')], max_length=3),
        ),
        migrations.AddField(
            model_name='attachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impresso.Job'),
        ),
    ]
