# Generated by Django 2.1.5 on 2019-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0024_searchquery_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name_plural': 'attachments'},
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='attachments',
        ),
    ]
