# Generated by Django 2.1.5 on 2019-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0025_auto_20190314_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='results',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='count_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
