# Generated by Django 2.1.8 on 2019-05-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0027_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectableitem',
            name='indexed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
