# Generated by Django 2.1.8 on 2019-06-05 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import impresso.models.uploadedImage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impresso', '0028_collectableitem_is_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('signature', models.TextField()),
                ('md5_checksum', models.CharField(db_index=True, max_length=32)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=impresso.models.uploadedImage.user_directory_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_last_modified'],
            },
        ),
        migrations.AlterField(
            model_name='collectableitem',
            name='content_type',
            field=models.CharField(choices=[('A', 'Article'), ('P', 'Page'), ('I', 'Issue'), ('M', 'Image')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('DCO', 'Delete collection'), ('IDX', 'Index collection in search engine'), ('EXP', 'Export collection as CSV'), ('EXP', 'Export query as CSV'), ('TES', '10 minutes countdown, 1 percent every 6 seconds'), ('IMG', 'Generate vector signature for the image and store the result in the db')], max_length=3),
        ),
    ]
