# Generated by Django 2.1.8 on 2019-06-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0029_auto_20190605_1600'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedimage',
            table='uploaded_images',
        ),
    ]
