# Generated by Django 2.1.8 on 2019-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0030_auto_20190605_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.TextField(default=''),
        ),
    ]
