# Generated by Django 3.0.1 on 2020-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0031_auto_20190617_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REA', 'ready'), ('RUN', 'running'), ('DON', 'Finished, no errors!'), ('ARC', 'Finished, archived by the user'), ('STO', 'Please stop'), ('RIP', 'Stopped by user! Rest IN Peace...'), ('ERR', 'Ops, errors!')], default='REA', max_length=3),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('DCO', 'Delete collection'), ('IDX', 'Index collection in search engine'), ('IDL', 'Index only collection for a few content items'), ('EXP', 'Export collection as CSV'), ('EXP', 'Export query as CSV'), ('TES', '10 minutes countdown, 1 percent every 6 seconds'), ('IMG', 'Generate vector signature for the image and store the result in the db')], max_length=3),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
