# Generated by Django 3.0.7 on 2020-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0032_auto_20200826_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('DCO', 'Delete collection'), ('IDX', 'Index collection in search engine'), ('IDL', 'Index only collection for a few content items'), ('EXP', 'Export collection as CSV'), ('EXP', 'Export query as CSV'), ('TES', '10 minutes countdown, 1 percent every 6 seconds'), ('IMG', 'Generate vector signature for the image and store the result in the db'), ('ITR', 'Sync collection to related TR passages')], max_length=3),
        ),
    ]
