# Generated by Django 3.0.7 on 2020-11-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0034_collectableitem_search_query_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectableitem',
            name='search_query_score',
            field=models.FloatField(blank=True, db_index=True, default=0.0, null=True),
        ),
    ]
