# Generated by Django 5.0.4 on 2024-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0035_auto_20201102_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('BCQ', 'Bulk collection from query'), ('BCT', 'Bulk collection from query TR passages'), ('DCO', 'Delete collection'), ('IDX', 'Index collection in search engine'), ('IDL', 'Index only collection for a few content items'), ('EXP', 'Export collection as CSV'), ('EXP', 'Export query as CSV'), ('TES', '10 minutes countdown, 1 percent every 6 seconds'), ('IMG', 'Generate vector signature for the image and store the result in the db'), ('ITR', 'Sync coll. to related TR passages'), ('RDX', 'Remove collection from solr index'), ('RTR', 'Remove coll. from SOLR TR index')], max_length=3),
        ),
    ]
