# Generated by Django 5.0.7 on 2024-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0037_datasetbitmapposition_userbitmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetbitmapposition',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datasetbitmapposition',
            name='bitmap_position',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
