# Generated by Django 5.0.7 on 2024-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0038_datasetbitmapposition_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbitmap',
            name='subscriptions',
            field=models.ManyToManyField(to='impresso.datasetbitmapposition'),
        ),
        migrations.AlterField(
            model_name='userbitmap',
            name='bitmap',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
