# Generated by Django 5.0.7 on 2024-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0039_userbitmap_subscriptions_alter_userbitmap_bitmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetbitmapposition',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userbitmap',
            name='bitmap',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
