# Generated by Django 5.0.4 on 2024-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0040_alter_datasetbitmapposition_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbitmap',
            name='date_accepted_terms',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
