# Generated by Django 5.0.7 on 2024-10-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0041_userbitmap_date_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbitmap',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='impresso.datasetbitmapposition'),
        ),
    ]
