# Generated by Django 5.0.8 on 2024-10-16 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0045_datasetbitmapposition_reviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='subscriber',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrequest',
            unique_together={('user', 'subscription')},
        ),
    ]
