# Generated by Django 5.0.8 on 2024-10-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0046_rename_subscriber_userrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
