# Generated by Django 5.1.4 on 2024-12-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0051_userrequestingchangeplan_userchangeplanrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequestingChangePlan',
        ),
    ]
