# Generated by Django 5.1.4 on 2024-12-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0053_alter_userchangeplanrequest_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchangeplanrequest',
            unique_together=set(),
        ),
    ]
