# Generated by Django 5.2 on 2025-05-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0054_alter_userchangeplanrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institutional_url',
            field=models.URLField(blank=True, null=True, verbose_name='Institutional URL'),
        ),
    ]
