# Generated by Django 5.2 on 2025-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0055_profile_affiliation_profile_institutional_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='search_query_hash',
            field=models.TextField(blank=True, help_text='Hash of the search query', null=True),
        ),
    ]
