# Generated by Django 5.2 on 2025-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('impresso', '0056_collection_search_query_hash'), ('impresso', '0057_remove_collection_search_query_hash_and_more')]

    dependencies = [
        ('impresso', '0055_profile_affiliation_profile_institutional_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='serialized_search_query',
            field=models.TextField(blank=True, help_text='Initital search query that generated the collection.', null=True),
        ),
    ]
