# Generated by Django 5.2 on 2025-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0056_collection_search_query_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='search_query_hash',
        ),
        migrations.AddField(
            model_name='collection',
            name='serialized_search_query',
            field=models.TextField(blank=True, help_text='Initital search query that generated the collection.', null=True),
        ),
    ]
