# Generated by Django 5.2.6 on 2025-11-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0056_collection_search_query_hash_squashed_0057_remove_collection_search_query_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='serialized_search_query',
            field=models.TextField(blank=True, help_text='Initial search query that generated the collection.', null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpecialMembershipDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bitmap_position', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userbitmap',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='impresso.specialmembershipdataset'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impresso.specialmembershipdataset'),
        ),
        migrations.DeleteModel(
            name='DatasetBitmapPosition',
        ),
    ]
