# Generated by Django 5.2.6 on 2025-11-13 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0058_alter_collection_serialized_search_query_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequest',
            new_name='UserSpecialMembershipRequest',
        ),
    ]
