# Generated by Django 5.2.10 on 2026-05-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0058_remove_userrequest_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='serialized_search_query',
            field=models.TextField(blank=True, help_text='Initial search query that generated the collection.', null=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
