# Generated by Django 5.2.8 on 2025-12-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0059_rename_userrequest_userspecialmembershiprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialmembershipdataset',
            options={'verbose_name': 'Special Membership Access', 'verbose_name_plural': 'Special Membership Accesses'},
        ),
        migrations.AlterModelOptions(
            name='userspecialmembershiprequest',
            options={'verbose_name': 'User Special Membership Request', 'verbose_name_plural': 'User Special Membership Requests'},
        ),
        migrations.AlterField(
            model_name='userspecialmembershiprequest',
            name='subscription',
            field=models.ForeignKey(help_text='The special membership dataset being requested', null=True, on_delete=django.db.models.deletion.SET_NULL, to='impresso.specialmembershipdataset'),
        ),
    ]
