# Generated by Django 5.2.10 on 2026-05-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0059_alter_collection_serialized_search_query_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaristaConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barista_session_id', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barista_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barista Conversation',
                'verbose_name_plural': 'Barista Conversations',
                'ordering': ['-date_last_modified'],
            },
        ),
    ]
