# Generated by Django 5.2.8 on 2025-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0060_alter_specialmembershipdataset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmembershipdataset',
            name='title',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterModelTable(
            name='specialmembershipdataset',
            table='impresso_datasetbitmapposition',
        ),
        migrations.AlterModelTable(
            name='userspecialmembershiprequest',
            table='impresso_userrequest',
        ),
    ]
