# Generated by Django 5.2.16 on 2026-07-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0062_alter_specialmembershipdataset_bitmap_position_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmembershipdataset',
            name='bitmap_position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
