# Generated by Django 5.2.16 on 2026-07-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("impresso", "0063_alter_specialmembershipdataset_bitmap_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
