# Generated by Django 5.2.16 on 2026-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresso', '0064_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmembershipdataset',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='specialmembershipdataset',
            name='data_provider',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specialmembershipdataset',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
